[package]
name = "scripten"
version = "0.0.1"
edition = "2021"

[lib]
name = "scripten"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]